export const fishList = [
  {
    name: "White Axolotl",
    chance: 40,
    type: "swimmer",
    image: "WhiteAxolotl.png",
    animation: ["WAIdle.png", "WAMove1.png"],
    codename: "WA",
    rarity: "Common",
  },
  {
    name: "Magikarp",
    chance: 30,
    type: "swimmer",
    image: "Magikarp.png",
    animation: ["MKIdle.png", "MKMove1.png"],
    codename: "MK",
    rarity: "Common",
  },
  {
    name: "Blue Pikmin",
    chance: 20,
    type: "walker",
    image: "BluePikmin.png",
    animation: ["BPIdle.png", "BPMove1.png"],
    codename: "BP",
    rarity: "Uncommon",
  },
  {
    name: "Poliwhirl",
    chance: 10,
    type: "swimmer",
    image: "Poliwhirl.png",
    animation: ["PWIdle.png", "PWMove1.png"],
    codename: "BP",
    rarity: "Rare",
  },
  {
    name: "Spongebob Banana",
    chance: 5,
    type: "floater",
    image: "SpongebobBanana.png",
    animation: ["SBIdle.png"],
    rarity: "Epic",
  },
];
